# Generated by Django 5.0 on 2023-12-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='start_date',
            new_name='release_date',
        ),
    ]
